name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
  schedule:
    # Once a week
    - cron: '0 0 * * 0'
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tags
        run: |
          echo "LATEST_TAG=ghcr.io/${GITHUB_REPOSITORY_OWNER@L}/${GITHUB_REPOSITORY@L}:latest" >> $GITHUB_ENV
      
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        env:
          LATEST_TAG: ${{ env.LATEST_TAG }}
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ env.LATEST_TAG }}

      - name: Run DNS Forwarder
        env:
          LATEST_TAG: ${{ env.LATEST_TAG }}
        run: docker run -d -p 8053:53/udp --name dns-forwarder ${{ env.LATEST_TAG }} 1.1.1.1

      - name: Test DNS Forwarder
        run: |
          sleep 10
          dig @localhost -p 8053 +time=1 +tries=3 microsoft.com
          if [ $? -ne 0 ]; then
            echo "DNS Forwarder test failed"
            exit 1
          fi

      - name: Stop DNS Forwarder
        run: docker stop dns-forwarder

      - name: Push Docker Image
        if: success() && github.ref == 'refs/heads/main'
        env:
          LATEST_TAG: ${{ env.LATEST_TAG }}
        run: docker push ${{ env.LATEST_TAG }}