name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      - name: Run DNS Forwarder
        run: docker run -d -p 8053:53/udp --name dns-forwarder ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest 1.1.1.1

      - name: Test DNS Forwarder
        run: |
          sleep 10
          dig @localhost -p 8053 +time=1 +tries=3 microsoft.com
          if [ $? -ne 0 ]; then
            echo "DNS Forwarder test failed"
            exit 1
          fi

      - name: Push Docker Image
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
